import Accordion from "react-bootstrap/Accordion";
import ListGroup from "react-bootstrap/ListGroup";
function FlushExample() {
    return (
        <Accordion flush>
            <Accordion.Item eventKey="0">
                <Accordion.Header>ปีการศึกษา-ภาคเรียน 2565-1</Accordion.Header>
                <Accordion.Body>
                    <ListGroup>
                        <div classname="accordion">
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiOWQyYTUzYTktYmYyNi00N2MzLTljMWItYjM4ZGNmMTQ0YWIyIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D&pageName=ReportSection"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนแยกชั้น,เพศ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiNDJkNWI5Y2ItYWE1NC00NmYwLTlkNDAtNGQzYTcwZDdhOTMwIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนจำแนกตามอายุ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiYjAxZDMwNzAtMzEwZC00NmE5LWEwZWYtOWFjMDVmZjkzODQwIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนพิการ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiYmQ0Mjk2MjYtMWQ5OS00YmM2LWJmNWUtYWIxZGI0N2VjYTNhIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนที่อยู่ห่างเกิน 3 กม.จำแนกตามการเดินทาง
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiY2JjYTQxNTItOWViNi00N2FiLWIwZmUtNGE4YTU2OWQ2MzM4IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนด้อยโอกาส
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMWU4NmNlY2ItMTU2NC00MjdhLWEzNDUtZGMwZDFkMTE2MGU3IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนขาดแคลน
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMDAxMWZmYTgtNmUzMi00NGExLThhMjQtZjM1YzAxZGM3NDk0IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนแยกตามสัญชาติ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiOTc2MjQwZjItNjg0Yy00NThlLTg3OGYtOWJhNTZhYzUyNTNjIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนแยกตามศาสนา
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMDc3NTFkMDAtZjliOS00ZDNmLTliYzktMTBlMGMxYzM3NzdjIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D&pageName=ReportSectionb2ffd9c1b6c52541e6a1"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนพักนอน
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiYThmYzA4OTctMTdlZS00OTBjLTliM2MtZTA0YjBjNDIyNDIyIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    ภาวะโภชนาการ ส่วนสูงตามเกณฑ์อายุ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiZGFmNmMwNTUtYjYxZi00MDkwLWFmYTgtM2FjY2FlYzNlNjZkIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    ภาวะโภชนาการ น้ำหนักตามเกณฑ์ส่วนสูง
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiNDk3OGZmNDgtNDRmZC00ODMzLTg1OTktZjU3Njk5OTkyMGYyIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนติด G
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMDY2ZDhiOWItMWRhYy00NmJiLThmMzYtYTQ2Y2I2ZWEwNjBiIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียจำนวนโรงเรียนที่มีไฟฟ้า/ไม่มีไฟฟ้าพิการ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiM2JiNTQyYmQtOTE1Yy00OTMzLTllNzUtYzM0ZjU0ZDVhMjk4IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนโรงเรียนที่ใช้น้ำประปา
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiNDQyZmM3Y2YtODQ5Yy00MjYwLThjOGEtOWZlYmY5OTQyMzFiIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนโรงเรียนที่ใช้อินเทอร์เน็ต
                                </a>
                            </ListGroup.Item>
                        </div>
                    </ListGroup>
                </Accordion.Body>
            </Accordion.Item>
            <Accordion.Item eventKey="1">
                <Accordion.Header>ปีการศึกษา-ภาคเรียน 2565-2</Accordion.Header>
                <Accordion.Body>
                    <ListGroup>
                        <div classname="accordion">
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiOWQyYTUzYTktYmYyNi00N2MzLTljMWItYjM4ZGNmMTQ0YWIyIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D&pageName=ReportSection"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนแยกชั้น,เพศ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiNDJkNWI5Y2ItYWE1NC00NmYwLTlkNDAtNGQzYTcwZDdhOTMwIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนจำแนกตามอายุ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiYjAxZDMwNzAtMzEwZC00NmE5LWEwZWYtOWFjMDVmZjkzODQwIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนพิการ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiYmQ0Mjk2MjYtMWQ5OS00YmM2LWJmNWUtYWIxZGI0N2VjYTNhIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนที่อยู่ห่างเกิน 3 กม.จำแนกตามการเดินทาง
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiY2JjYTQxNTItOWViNi00N2FiLWIwZmUtNGE4YTU2OWQ2MzM4IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนด้อยโอกาส
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMWU4NmNlY2ItMTU2NC00MjdhLWEzNDUtZGMwZDFkMTE2MGU3IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนขาดแคลน
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMDAxMWZmYTgtNmUzMi00NGExLThhMjQtZjM1YzAxZGM3NDk0IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนแยกตามสัญชาติ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiOTc2MjQwZjItNjg0Yy00NThlLTg3OGYtOWJhNTZhYzUyNTNjIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนแยกตามศาสนา
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMDc3NTFkMDAtZjliOS00ZDNmLTliYzktMTBlMGMxYzM3NzdjIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D&pageName=ReportSectionb2ffd9c1b6c52541e6a1"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนพักนอน
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiYThmYzA4OTctMTdlZS00OTBjLTliM2MtZTA0YjBjNDIyNDIyIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    ภาวะโภชนาการ ส่วนสูงตามเกณฑ์อายุ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiZGFmNmMwNTUtYjYxZi00MDkwLWFmYTgtM2FjY2FlYzNlNjZkIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    ภาวะโภชนาการ น้ำหนักตามเกณฑ์ส่วนสูง
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiNDk3OGZmNDgtNDRmZC00ODMzLTg1OTktZjU3Njk5OTkyMGYyIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียนติด G
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiMDY2ZDhiOWItMWRhYy00NmJiLThmMzYtYTQ2Y2I2ZWEwNjBiIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนนักเรียจำนวนโรงเรียนที่มีไฟฟ้า/ไม่มีไฟฟ้าพิการ
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiM2JiNTQyYmQtOTE1Yy00OTMzLTllNzUtYzM0ZjU0ZDVhMjk4IiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนโรงเรียนที่ใช้น้ำประปา
                                </a>
                            </ListGroup.Item>
                            <ListGroup.Item>
                                <a
                                    href="https://app.powerbi.com/view?r=eyJrIjoiNDQyZmM3Y2YtODQ5Yy00MjYwLThjOGEtOWZlYmY5OTQyMzFiIiwidCI6ImNmODFmMWRmLWRlNTktNGMyOS05MWRhLWEyZGZkMDRhYTc1MSIsImMiOjEwfQ%3D%3D"
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    จำนวนโรงเรียนที่ใช้อินเทอร์เน็ต
                                </a>
                            </ListGroup.Item>
                        </div>
                    </ListGroup>
                </Accordion.Body>
            </Accordion.Item>
        </Accordion>
    );
}

export default FlushExample;

// /*ตรงนี้ axios ข้อมูลจาก DataBase*/
